Fix errors when automation scripts being loaded and os.execute not working
TypesettingTools/Aegisub pull request #156
Opened 2022-04-21 09:03 UTC by baonguyen0703

Line 68: Syntax error -> without the parentheses, some automation scripts will raise the error "cannot convert 'function' to 'int'" when being loaded

![Aegisub 9262 error 1](https://user-images.githubusercontent.com/98341055/164414238-3238d1e8-2dcc-45d4-a4a6-8d949cb7867c.png)

Line 72: Will raise the error "attempt to concatenate 'string' and 'char *'

![Aegisub 9262 error 2](https://user-images.githubusercontent.com/98341055/164414706-3f459395-3364-4705-b5b5-5c06bbff144d.png)

Line 128-129: code is changed so the command can be executed

2022-06-05 23:22 UTC, CoffeeFlux commented
What version of Lua are you linking here? I don't recall this happening locally, so I'd like to know why that differs before merging anything.

2022-06-08 06:51 UTC, baonguyen0703 commented
> What version of Lua are you linking here? I don't recall this happening locally, so I'd like to know why that differs before merging anything.

I used aegisub.log(_VERSION) in a lua script and it showed Lua 5.1  

![image](https://user-images.githubusercontent.com/98341055/172548541-9b8b868c-2af0-4958-8f6c-ef200e95ccb0.png)

2022-06-08 08:09 UTC, CoffeeFlux requested changes
Now that I'm actually looking at this, your changes are correct and I have no idea how this didn't error out before. Maybe I committed the wrong version somehow? Anyway, just a couple comments.

2022-06-08 10:00 UTC, baonguyen0703 commented
I have updated the code as requested

2022-06-08 15:36 UTC, merged